#开发
spring:
  activemq:
    broker-url: tcp://47.104.98.61:61616
    user: admin
    password: admin
  jms:
    listener:
      concurrency: 15
      max-concurrency: 20
  datasource:
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 60
      minimum-idle: 10
    url: jdbc:mysql://139.129.242.146:3306/pointcoil?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  data:
    mongodb:
      host: 139.129.242.146
      port: 27017
      username: test
      password: wushuang
      database: pointcoil
  servlet:
    multipart:
      # 上传一个文件最大值,默认1Mb
      max-file-size: 300MB
      # 上传多个文件最大值,100Mb,默认10Mb
      max-request-size: 300MB
  redis:
    host: 127.0.0.1
    password: admin
    timeout: 10000
    port: 6380
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: true
myqueue : queue_SplitExcelPath
point-coil:
  #url: http://dxq.hzsw-tech.com/pointcoil/img/pointcoil_img/
  url: https://www.hzdxq.cn/pointcoil/img/pointcoil_img/
  image-upload-url: /code/img/pointcoil_img
  redis:
    shop-prefix: shouwang_shop_
    home-page-init: shouwang_home_page_init
    home-page-init-news: shouwang_home_page_init_news
    home-page-init-industry: shouwang_home_page_init_industry
    phone-search: shouwang_shop_hot_search_commodities
    to-examine-email: shouwang_to_examine_email
    login-home-key: shouwang_login_key
    is-register: shouwang_is_register
    business-init: shouwang_businessInit
    business-zone-page-init: shouwang_business_zone_page_init
    label-page-init: shouwang_label_page_init
    community-post-page-init: shouwang_community_post_page_init
    my-Business-Zone: shouwang_my_Business_Zone
    first-img: shouwang_firstImg
    is-account-sub: shouwang_is_account_sub
 # wx:
    #小程序的第三方appid
  #  appId: wx4249ce4b7f44703d
    #微信登陆的AppId
   # WXAppID: wx042b052013ab970b
    # WXAppSecret: 49aea4ecb917daac59139797a439cb7e




