#生产
spring:
  activemq:
    broker-url: tcp://47.104.98.61:61616
    user: admin
    password: admin
  datasource:
    url: jdbc:mysql://47.96.191.173:3306/clothing_store_dev?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8
    username: test
    password: 1qaz!QAZ
  servlet:
    multipart:
      # 上传一个文件最大值,默认1Mb
      max-file-size: 20MB
      # 上传多个文件最大值,100Mb,默认10Mb
      max-request-size: 100MB
  redis:
    host: 106.14.218.31
    password: admin
queue: pointMsg-queue01
clothing-store:
  image-upload-path:
    prefix: /upload/clothingstore
    common: /app/
    factory: /app/factory/
    wholesaler: /app/wholesaler/
    commodity: /app/commodity/
    post: /app/post/
    post-comment: /app/post-comment/
    order-comment: /app/order-comment/
    recommend: /app/recommend/
    avatar: /app/avatar/
  image-upload-url: /clothingstore/
  app:
    redis:
      shop-prefix: shouwang_shop_
      home-page-init: shouwang_home_page_init
      hot-search: shouwang_shop_hot_search_commodities
      sort-page-init: shouwang_sort_page_init
      community-post-page-init: shouwang_community_post_page_init